### ISSUE TITLE
I am a beginner in electron, how can I use your project?

### ISSUE THREAD

**Issue by aaxx255** [herberttn/bytenode-webpack-plugin#10]
I haven't learned how to encrypt my sample project.
Please help me,Think you

**Comment by herberttn** [comment]
@aaxx255 hello! Thank you for the interest!

This project is a `webpack` plugin, so you simply have to add it to the list of plugins in your `webpack` configuration, as shown in our documentation.

There are several different ways of building your electron application, with and without `webpack`. I'd suggest you try and learn a little bit about `electron-forge` and/or `electron-builder`, which are the most commonly used projects to help doing that.

But beware: this project only supports `webpack` v4 as of now, which translates into `electron-forge` v5 if you're using that.
