### ISSUE TITLE
Source code leak

### ISSUE THREAD

**Issue by m4w1s** [herberttn/bytenode-webpack-plugin#15]
Hello! It seems that version >=2.0.0 of this module, after adding support for webpack 5, includes the source code in the final build files.
I also tested the examples in this repository to exclude a possible issue with my configuration, and got the same results.
For reference I tested this example for webpack 4 and it worked just fine: https://github.com/spaceagetv/electron-bytenode-example

**Comment by jjeff** [comment]
I have confirmed this in the [electron-bytenode-example `webpack5` branch](https://github.com/spaceagetv/electron-bytenode-example/tree/feature/webpack5). I've added text to the source code which should not appear in the final output. It currently **does** appear in the final output.

To test:
1. Check out the `webpack5` branch, then run `npm run package` to package. 
2. Then search through the `out` directory for the string "SOURCE-TEST". It is appearing in all of the "loader" files (.../main/index.js, .../renderer/main_window/index.js, and .../renderer/main_window/preload.js)

Needless to say, this is a big problem.

**Comment by dantatepico** [comment]
Can also confirm I'm seeing the same thing.

In previous versions the generated `index.js` would simply be a shim that then loaded the `index.compiled.jsc` file.

However in version 2.2.0 the generated `index.js` just contains the plain javascript code.

**Comment by zhangyandong** [comment]
Same problem

**Comment by jjeff** [comment]
I've updated the  [electron-bytenode-example `webpack5` branch](https://github.com/spaceagetv/electron-bytenode-example/tree/feature/webpack5) to include a source leak unit test. It's currently failing. But once we get it passing again, we'll know that the source isn't leaking into the JS output.
