### ISSUE TITLE
Windows Electron bug?

### ISSUE THREAD

**Issue by jjeff** [herberttn/bytenode-webpack-plugin#18]
We're seeing an error in the electron-bytenode-example project when launching on Windows:
https://github.com/spaceagetv/electron-bytenode-example/issues/31

Haven't quite narrowed this issue down yet, but I'm guessing that it's a bytenode-webpack-plugin issue… and probably something related to the Windows-specific code in [loaders.ts](https://github.com/herberttn/bytenode-webpack-plugin/blob/main/src/loaders.ts). If it's a loader issue, it's probably not specific to Electron.

**Comment by JohnWeisz** [comment]
I don't know if it's related, but Windows in general seems to produce the wrong module path in the bootstrapper bundle:

```
((module) => {
  "use strict";
  module.exports = require("C:\path\to\app\build\renderer.compiled.jsc");
})
```

2 problems here:

 1. Unescaped backslashes -- probably self explanatory
 2. The module path will not make sense once the app is packed -- you need to do a string replace here during build to make it work

Note: if you edit this file to update the module path, everything else works correctly.

**Comment by jjeff** [comment]
This is different than the problem I'm [seeing here](https://github.com/herberttn/bytenode-webpack-plugin/pull/19#issuecomment-1364307643). I was getting an escaped, but *absolute*, path to my Typescript entry file (for the main process).

**Comment by jlcarvalho** [comment]
I'm having the same issue here, did you found a workaround? @jjeff
